# Generated by Django 4.0 on 2022-01-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variatoin_category',
            new_name='variation_category',
        ),
    ]
